# Generated by Django 3.2 on 2022-09-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subtitle',
            field=models.TextField(max_length=500),
        ),
    ]
